### ISSUE TITLE
Cant build for Nuinit 

### ISSUE THREAD

**Issue by aramosipyan** [TestMonkeys/Assert#1]
To run project against nunit framework i had to download sources and set some attributes 
Can we have nUnit ready binary package instead?

**Comment by costea32** [comment]
Could you please give more info?

**Comment by costea32** [comment]
If you're looking for a compiled lib of NUnit assert extensions you can find it here: https://www.nuget.org/packages/TestMonkeys.NExtensions/

**Comment by aramosipyan** [comment]
Thanks it helped
